config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "lists#index"
	resources :lists do
		member do
			patch :complete
	    end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	validates_presence_of :title,:date,:description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :set_list, :only =>[:edit,:update,:destroy,:complete]
	def index
		@lists = List.all
	end


    def complete 
    if @list.completed == false
       @list.update_attribute(:completed, true)
    else
      @list.update_attribute(:completed, false)
    end
    redirect_to lists_path(@list)
    end

    def new
    	@list = List.new    	
    end

    def create
    	@list = List.new(list_params)
    	if@list.save
    	  redirect_to lists_path
    	else
    	  render :new
    	end
    end


    def edit
    end

    def update
        if @list.update_attributes(list_params)

           redirect_to lists_path
        else
           render :edit
        end
    end

    def destroy
         @list.destroy

         redirect_to lists_url
    end


    private

    def set_list
    	@list = List.find(params[:id])
    end
    def list_params
    	params.require(:list).permit(:title, :date, :description)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="form container">
<%= form_for @list do |f| %>
<div class="form-group"> 
  <%= f.label :title, "Title" %>
  <%= f.text_field :title,class:"form-control" %>
</div>

<div class="form-group">
  <%= f.label :date, "Deadline" %>
  <%= f.text_field :date ,class:"form-control"%>
</div>

<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description,class:"form-control" %>
</div>

<div class="form-group">
  <%= f.submit %>
</div>

<%= link_to lists_path do %>
    <button type="button" class="btn btn-default btn-sm">
      <span class="glyphicon glyphicon-file"></span> Back to the index 
    </button>
<%end %>

<% end %>



</div>




<% if @list.errors.present? %>
  <ul>
    <% @list.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

app/views/lists/edit.html.erb
<style>
	h2{color: blue; text-align: center;}
</style>

<h2>修改任務,希望你不是因為想要耍廢而來延長時間...</h2>
<%= render :partial => "form" %>

app/views/lists/index.html.erb
<style>
	.add{text-align: center;}
	h4{color: gray;}
	h2,h4{text-align: center; margin-bottom: 20px;}

</style>

<h2>任務清單</h2>
<h4>每天都有做努力,你會看到自己的改變,那怕只是成長一點點</h4>
<table class="table table-striped">
    <tr>
        <td>任務狀態</td>
        <td>任務</td>
        <td>任務期限</td>
        <td>任務內容</td>
        <td>任務編輯</td>
        <td>任務刪除</td>
    </tr>

    <% @lists.each do |list| %>
      <tr>
        <% if list.completed %>
          <td>
            <%= link_to complete_list_path(list), method: :patch do %>
              <span class="glyphicon glyphicon-check"></span>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to complete_list_path(list), method: :patch do %>
              <span class="glyphicon glyphicon-unchecked"></span>
            <% end %>
          </td>
        <% end %>

        <td><%= list.title %></td>
        <td><%= list.date %></td>
        <td><%= list.description %></td>
        <td>
          <%= link_to edit_list_path(list) do %>
             <button type="button" class="btn btn-default btn-sm">
             <span class="glyphicon glyphicon-edit"></span> Edit
             </button>
             <%end%>
        </td>
        
        <% if Time.now.to_date <= list.date %>
        <td>  
        <%= link_to list_path(list), method: :delete, data:{ confirm: "Are you sure?" } do%> 
           <button type="button" class="btn btn-default btn-sm">
           <span class="glyphicon glyphicon-trash"></span> Trash 
           </button>
           <%end%>    
        </td>

        <%else%>
        <td>expired</td>
        <%end%>
  
      <tr>

<% end %>
</table>

<div class="add">
<%= link_to new_list_path  do%>
        <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-plus"></span> New Challenge
        </button>
        <% end %>
</div>

app/views/lists/new.html.erb
<style>
	h2{color: blue; text-align: center;}
</style>

<h2>接受新任務的挑戰吧</h2>
<%= render :partial => "form" %>